---
- name: Set fact
  set_fact:
    ansible_host: "{{ item.value.host }}"
- name: The Device is 
  debug:
    msg: "{{ item.key }}"
- name: "Retrive Device Versions" 
  ios_command:
    commands:
     - show version
  register: output

- name: "Show Device Versions"
  debug:
    msg: "{{ output['stdout_lines'][0] }}"
    #msg: "{{ output['stdout'][0] }}"
#- name: "Assert expected Image version in device "
#  assert:
#    that: 
#     - " '16.9.2' in output['stdout'][0]"