---

- name: "GET-Running Config and Save them "
  gather_facts: 'no'
  hosts: "{{ dev }}"
  vars:
    ansible_python_interpreter: "/usr/local/bin/python3"
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: "sdaadmin"
    ansible_password: "C!sc0123"
    ansible_become: "yes"
    ansible_become_method: enable
    ansible_became_password: "C!sc0123"
    ansible_stdout_callback: debug
  
  tasks:
    - name: "TASK0: Get timestamp from the system"
      shell: "date +%d%m%Y"
      register: tstamp

    - name: "TASK1: Stop Monitor Capture "
      ios_command:
        commands: 
          - monitor capture CaptureA stop

    - name: "TASK2: Export Packet Capture to Flash"
      ios_command:
        commands: 
          - command: "  monitor capture CaptureA export location flash:CaptureA.pcap \n"
            answer: "\r" 

    - name: "TASK3: Check Export and Wait for it to finish"
      ios_command:
        commands: 
          - monitor capture CaptureA export status
        wait_for:
          - result[0] contains "No export currently active"
    
    - name: "TASK4: Make Sure Ftp Server parameters are configured"
      ios_config:
        lines:
          - ip ftp username root
          - ip ftp password aka 
          - ip ftp source-interface gi0/0
          - file prompt quiet 

    - name: "TASK5: Transfer CaptureA to ftp://10.48.172.80/SDA/Captures/ and delete Capture"
      ios_command:
        commands: 
          - copy CaptureA.pcap ftp://10.48.172.80/SDA/Captures/{{ inventory_hostname }}-{{ tstamp.stdout }}.pcap
          - no monitor capture CaptureA
    - name: "TASK6: Get today Captures on my system"
      shell: get-captures.sh
      register: result