---
- name: Set Enviroment facts
  set_fact:
    ansible_host: "{{ item.value.mgmt_ip }}"
- name: Config Gigabit Ethernet2
  ios_config:
    lines:
      - ip address {{ item.value.g2_ip }} 255.255.255.0
      - no shutdown
      - mtu 9000
      - bfd interval 100 min_rx 100 multiplier 3
      - ip router isis
    parents: interface GigabitEthernet2
- name: Config LoopBack0
  ios_config:
    lines:
      - ip address {{ item.value.l0_ip }} 255.255.255.255
      - ip router isis
    parents: interface LoopBack0